import 'package:flutter/material.dart';

class Themes {
  static final ThemeData lightMode = ThemeData(
    backgroundColor: Colors.white,
    scaffoldBackgroundColor: Colors.white,
    // applyElevationOverlayColor: ,
    // bannerTheme: ,
    // bottomAppBarColor: ,
    // bottomAppBarTheme: ,
    bottomNavigationBarTheme: BottomNavigationBarThemeData(
      showUnselectedLabels: true,
      backgroundColor: Colors.white,
      type: BottomNavigationBarType.fixed,
      elevation: 2,
      // selectedIconTheme: IconThemeData(
      //   color: CustomColor.violet7F3DFF,
      //   size: 24,
      // ),
      // selectedItemColor: CustomColor.violet7F3DFF,
      // selectedLabelStyle: TextStyle(
      //   fontFamily: 'Montserrat',
      //   color: CustomColor.violet7F3DFF,
      //   fontSize: 12,
      //   letterSpacing: 0.5,
      //   fontWeight: FontWeight.w500,
      // ),
      unselectedIconTheme: IconThemeData(
        color: Colors.black.withOpacity(0.4),
        size: 24,
      ),
      unselectedItemColor: Colors.black.withOpacity(0.4),
      unselectedLabelStyle: TextStyle(
        fontFamily: 'Montserrat',
        color: Colors.black.withOpacity(0.4),
        fontSize: 12,
        letterSpacing: 0.5,
        fontWeight: FontWeight.w400,
      ),
    ),
    // bottomSheetTheme: ,
    // brightness: ,
    // buttonBarTheme: ,
    // buttonTheme: ,
    // canvasColor: ,
    // cardColor: ,
    // cardTheme: ,
    // checkboxTheme: ,
    // chipTheme: ,
    // colorScheme: ,
    // cupertinoOverrideTheme: ,
    // dataTableTheme: ,
    // dialogBackgroundColor: ,
    // dialogTheme: ,
    // disabledColor: ,
    // dividerColor: ,
    // dividerTheme: ,
    // elevatedButtonTheme: ,
    // errorColor: ,
    // floatingActionButtonTheme: FloatingActionButtonThemeData(
    //   backgroundColor: CustomColor.violet7F3DFF,
    // ),
    // focusColor: ,
    // fontFamily: ,
    // highlightColor: ,
    // hintColor: ,
    // hoverColor: ,
    // iconTheme: IconThemeData(color: CustomColor.yellowFCAC12),
    // indicatorColor: ,
    // materialTapTargetSize: ,
    // navigationRailTheme: ,
    // outlinedButtonTheme: ,
    // pageTransitionsTheme: ,
    // platform: ,
    // popupMenuTheme: ,
    // primaryColor: ,
    // primaryColorBrightness: ,
    // primaryColorDark: ,
    // primaryColorLight: ,
    // primaryIconTheme: ,
    // primarySwatch: ,
    // primaryTextTheme: ,
    // progressIndicatorTheme: ,
    // radioTheme: ,
    // scrollbarTheme: ,
    // secondaryHeaderColor: ,
    // selectedRowColor: ,
    // shadowColor: ,
    // sliderTheme: ,
    // snackBarTheme: SnackBarThemeData(
    //   actionTextColor: Colors.white,
    //   backgroundColor: CustomColor.violet7F3DFF,
    //   behavior: SnackBarBehavior.floating,
    //   elevation: 0,
    //   contentTextStyle: TextStyle(
    //     fontFamily: 'Montserrat',
    //     color: Colors.white,
    //     fontWeight: FontWeight.w400,
    //   ),
    // ),
    // splashColor: ,
    // splashFactory: ,
    // switchTheme: ,
    // tabBarTheme: ,
    // textButtonTheme: ,
    // textSelectionTheme: ,
    // textSelectionTheme: TextSelectionThemeData(
    //   cursorColor: CustomColor.yellowFCAC12,
    //   selectionHandleColor: CustomColor.yellowFCAC12,
    //   selectionColor: CustomColor.yellowFCAC12,
    // ),
    // textTheme: ,
    // timePickerTheme: ,
    // toggleButtonsTheme: ,
    // toggleableActiveColor: ,
    // tooltipTheme: ,
    // typography: ,
    // unselectedWidgetColor: ,
    // visualDensity: ,
    // appBarTheme: AppBarTheme(
    //   systemOverlayStyle:
    //       SystemUiOverlayStyle(statusBarColor: CustomColor.violet7F3DFF),
    //   backgroundColor: CustomColor.violet7F3DFF,
    //   centerTitle: true,
    //   elevation: 2,
    //   foregroundColor: Colors.white,
    //   titleTextStyle: TextStyle(
    //     fontFamily: 'Montserrat',
    //     color: Colors.white,
    //     fontSize: 20,
    //     letterSpacing: 0.5,
    //     fontWeight: FontWeight.w400,
    //   ),
    //   iconTheme: IconThemeData(
    //     color: Colors.white,
    //     size: 24,
    //   ),
    //   actionsIconTheme: IconThemeData(
    //     color: Colors.white,
    //     size: 24,
    //     opacity: 0,
    //   ),
    // ),
  );
}